### ISSUE TITLE
More Documentation Required

### ISSUE THREAD

**Issue by dbjpanda** [prappo/wordpress-plugin-boilerplate#4]
Hi @prappo Nice initiative. I wanted to try it out. But I guess, there are so many unwanted things like Docs, Artworks etc. Well, I don't know which files/folders are required if I wanted to kickstart with a new plugin. So I would appreciate if you can add detail about Files and folder structure. Which files/folders can I delete or modify to start my own plugin.

**Comment by prappo** [comment]
@dbjpanda Thank you for your interest. I will update the document, but here are some quick tips: `npm run release` will remove unnecessary folders and files, generating a usable plugin in the `release` folder.

**Comment by dbjpanda** [comment]
@prappo Thank you for adding the folder structure. But what I meant initially was to explain about your folder structure. E.g what is database, what you put inside that? There are already few files like accounts. Do I need that? And so on. Appreciate your time.
